[package]
name = "hera-desktop"
version = "0.1.0"
edition = "2021"

[lib]
name = "hera_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "hera-desktop"
path = "src/main.rs"

[dependencies]
hera-runner = { path = "../runner" }
tauri = { version = "1.6", features = [
    "dialog-open", "dialog-save", "shell-open",
    "window-set-fullscreen", "window-minimize", "window-unminimize",
    "window-maximize", "window-unmaximize", "window-close",
    "window-hide", "window-show",
] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
anyhow = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
uuid = { version = "1", features = ["v4"] }
walkdir = "2"
toml = "0.8"
base64 = "0.22"
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }

[features]
# used by tauri
custom-protocol = ["tauri/custom-protocol"]

[build-dependencies]
tauri-build = { version = "1.5", features = [] }
